# Whether to protect waxed blocks from fire spread
enable-fire-spread-protection: true

# Distance (taxicab) to show particles on waxed blocks to players holding honeycombs
particle-range: 20

# Materials that require one honeycomb to wax and guarantee one honeycomb drop upon destruction
# Materials list: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
waxable-materials:
  - "COMPARATOR"
  - "LEVER"
  - "REPEATER"
# Any Material ending with these suffixes will be added to waxable-materials
waxable-materials-suffixes:
  - "_FENCE_GATE"
  - "_DOOR"
  - "_TRAPDOOR"

# Materials that, when waxed, have only a specified chance of using the honeycomb
chance-based-waxable-materials:
  - "BOOKSHELF"
  - "HAY_BLOCK"
# Any Material ending with these suffixes will be added to chance-based-waxable-materials
chance-based-waxable-materials-suffixes:
  - "_WOOD"
  - "_PLANKS"
  - "_LOG"
  - "_LEAVES"

# Percent consumption and drop chances for chance-based waxable materials (0 - 100)
honeycomb-consumption-chance: 10
honeycomb-drop-chance: 5

# Rate in minutes to save waxed block data to world_data files. Set to 0 to disable autosave.
# world_data files are saved on server shutdown regardless of this value.
autosave-rate: 5

# Whether to send a message to players introducing the plugin upon picking up a honeycomb for the first time.
# The introductory message is sent only once per player. Introduced players are tracked in introduced_players.json
enable-introductory-message: true
