name: HoneyGuard
version: '1.0.0'
main: gg.elg.honeyGuard.HoneyGuard
api-version: '1.21'
author: Elgenzay
description: Extends honeycombs to make blocks noninteractive with optional fire spread prevention.
website: https://github.com/Elgenzay/honeyguard
commands:
  honeyguard:
    description: Display help information for the HoneyGuard plugin
    usage: /honeyguard